name: Continuous integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-ubuntu:
    name: Tests (Ubuntu)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run C++ tests
        run: ./test-cpp.sh
      - name: Run Rust tests
        run: ./test-rust.sh
        if: always()
      - name: Run Python tests
        run: python3 python/primes.py
        if: always()